# Generated by Django 5.2 on 2025-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
